// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wasla.Infrastructure.Persistence.Central;

#nullable disable

namespace Wasla.Infrastructure.Persistence.Central.Migrations
{
    [DbContext(typeof(CentralDbContext))]
    [Migration("20260621130300_AddPrintBridgeSetupDeviceSelection")]
    partial class AddPrintBridgeSetupDeviceSelection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Wasla.Domain.Entities.Central.BusinessType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("BusinessTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "restaurant",
                            DisplayName = "Restoran",
                            IsActive = true,
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "fast-food",
                            DisplayName = "Fast food",
                            IsActive = true,
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "cafe",
                            DisplayName = "Kafe",
                            IsActive = true,
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "dessert",
                            DisplayName = "Tatlıcı",
                            IsActive = true,
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "bakery",
                            DisplayName = "Pastane",
                            IsActive = true,
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Code = "pide-lahmacun",
                            DisplayName = "Pide / Lahmacun",
                            IsActive = true,
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Code = "doner",
                            DisplayName = "Döner",
                            IsActive = true,
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            Code = "pizza",
                            DisplayName = "Pizza",
                            IsActive = true,
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 9,
                            Code = "burger",
                            DisplayName = "Burger",
                            IsActive = true,
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 10,
                            Code = "sushi",
                            DisplayName = "Sushi",
                            IsActive = true,
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 11,
                            Code = "home-cooking",
                            DisplayName = "Ev yemekleri",
                            IsActive = true,
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 12,
                            Code = "other",
                            DisplayName = "Diğer",
                            IsActive = true,
                            SortOrder = 12
                        });
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.CentralAdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("IX_CentralAdminUsers_NormalizedEmail");

                    b.ToTable("CentralAdminUsers", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneAreaCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PlateCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "Name")
                        .IsUnique();

                    b.HasIndex("CountryCode", "PlateCode")
                        .IsUnique()
                        .HasFilter("[PlateCode] IS NOT NULL");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId", "Name")
                        .IsUnique();

                    b.ToTable("Districts", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.Neighborhood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("ExternalCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId", "Name")
                        .IsUnique();

                    b.ToTable("Neighborhoods", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.PendingRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AddressNote")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BuildingNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("BusinessEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BusinessPhone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BusinessPhoneType")
                        .HasColumnType("int");

                    b.Property<string>("BusinessType")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("DoorNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Floor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LocationUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("NeighborhoodId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OwnerFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("PaymentFailedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaymentSucceededAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PrimaryDomain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ProvisionedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SimulatedPaymentReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("StreetId")
                        .HasColumnType("int");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("DatabaseName")
                        .HasDatabaseName("IX_PendingRegistrations_DatabaseName");

                    b.HasIndex("DistrictId");

                    b.HasIndex("NeighborhoodId");

                    b.HasIndex("OwnerEmail")
                        .HasDatabaseName("IX_PendingRegistrations_OwnerEmail");

                    b.HasIndex("Slug")
                        .HasDatabaseName("IX_PendingRegistrations_Slug");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PendingRegistrations_Status");

                    b.HasIndex("StreetId");

                    b.ToTable("PendingRegistrations", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.PendingRegistrationBusinessType", b =>
                {
                    b.Property<Guid>("PendingRegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BusinessTypeId")
                        .HasColumnType("int");

                    b.HasKey("PendingRegistrationId", "BusinessTypeId");

                    b.HasIndex("BusinessTypeId");

                    b.ToTable("PendingRegistrationBusinessTypes", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.PrintBridgeDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastIpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MachineName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PrinterName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("nvarchar(88)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_PrintBridgeDevices_TenantId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_PrintBridgeDevices_TokenHash");

                    b.ToTable("PrintBridgeDevices", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.PrintBridgeSetupSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("nvarchar(88)");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompletionCredentialHash")
                        .HasMaxLength(88)
                        .HasColumnType("nvarchar(88)");

                    b.Property<bool>("ConnectionVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExchangedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("PrintBridgeDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ServerUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SetupMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique()
                        .HasDatabaseName("IX_PrintBridgeSetupSessions_CodeHash");

                    b.HasIndex("ExpiresAtUtc")
                        .HasDatabaseName("IX_PrintBridgeSetupSessions_ExpiresAtUtc");

                    b.HasIndex("PrintBridgeDeviceId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_PrintBridgeSetupSessions_TenantId");

                    b.ToTable("PrintBridgeSetupSessions", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.Street", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NeighborhoodId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("StreetType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NeighborhoodId", "Name", "StreetType")
                        .IsUnique()
                        .HasFilter("[StreetType] IS NOT NULL");

                    b.ToTable("Streets", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BillingPaymentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EncryptedConnectionString")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("EncryptionKeyVersion")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastMigrationAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastMigrationResult")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PrimaryDomain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProvisioningStatus")
                        .HasColumnType("int");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SubscriptionStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Tenants_IsActive");

                    b.HasIndex("PrimaryDomain")
                        .IsUnique()
                        .HasDatabaseName("IX_Tenants_PrimaryDomain");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("IX_Tenants_Slug");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.TenantMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BillingPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BusinessPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BusinessType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CurrentPeriodEndsAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnerEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_TenantMemberships_TenantId");

                    b.ToTable("TenantMemberships", (string)null);
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.District", b =>
                {
                    b.HasOne("Wasla.Domain.Entities.Central.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.Neighborhood", b =>
                {
                    b.HasOne("Wasla.Domain.Entities.Central.District", "District")
                        .WithMany("Neighborhoods")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.PendingRegistration", b =>
                {
                    b.HasOne("Wasla.Domain.Entities.Central.City", null)
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wasla.Domain.Entities.Central.District", null)
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wasla.Domain.Entities.Central.Neighborhood", null)
                        .WithMany()
                        .HasForeignKey("NeighborhoodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Wasla.Domain.Entities.Central.Street", null)
                        .WithMany()
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.PendingRegistrationBusinessType", b =>
                {
                    b.HasOne("Wasla.Domain.Entities.Central.BusinessType", "BusinessType")
                        .WithMany()
                        .HasForeignKey("BusinessTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Wasla.Domain.Entities.Central.PendingRegistration", "PendingRegistration")
                        .WithMany("BusinessTypes")
                        .HasForeignKey("PendingRegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessType");

                    b.Navigation("PendingRegistration");
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.PrintBridgeDevice", b =>
                {
                    b.HasOne("Wasla.Domain.Entities.Central.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.PrintBridgeSetupSession", b =>
                {
                    b.HasOne("Wasla.Domain.Entities.Central.PrintBridgeDevice", "Device")
                        .WithMany()
                        .HasForeignKey("PrintBridgeDeviceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Wasla.Domain.Entities.Central.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.Street", b =>
                {
                    b.HasOne("Wasla.Domain.Entities.Central.Neighborhood", "Neighborhood")
                        .WithMany("Streets")
                        .HasForeignKey("NeighborhoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Neighborhood");
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.TenantMembership", b =>
                {
                    b.HasOne("Wasla.Domain.Entities.Central.Tenant", "Tenant")
                        .WithOne()
                        .HasForeignKey("Wasla.Domain.Entities.Central.TenantMembership", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.City", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.District", b =>
                {
                    b.Navigation("Neighborhoods");
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.Neighborhood", b =>
                {
                    b.Navigation("Streets");
                });

            modelBuilder.Entity("Wasla.Domain.Entities.Central.PendingRegistration", b =>
                {
                    b.Navigation("BusinessTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
