<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Wasla.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    <PackageReference Include="Polly" Version="8.4.2" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageReference Include="MailKit" Version="4.16.0" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wasla.Application\Wasla.Application.csproj" />
    <ProjectReference Include="..\Wasla.Domain\Wasla.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Wasla.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="ReferenceData/turkey-reference-data.json" />
    <EmbeddedResource Include="Platform/Mock/Scenarios/*.json">
      <WithCulture>false</WithCulture>
    </EmbeddedResource>
    <EmbeddedResource Include="Email/Templates/*.html">
      <WithCulture>false</WithCulture>
    </EmbeddedResource>
    <EmbeddedResource Include="Email/Templates/*.txt">
      <WithCulture>false</WithCulture>
    </EmbeddedResource>
  </ItemGroup>

</Project>
